site_name: Airflow-Docker Studies
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Modo Claro

    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Modo Escuro

  language: en

plugins:
  - search
  - mkdocstrings:
      default_handler: python